### ISSUE TITLE
workflow's environment variables  is Invalid，maybe I  used Wrong way

### ISSUE THREAD

**Issue by xuetengfei** [bjrnt/alfred-project-manager#1]
workflow's environment variables

**Comment by bjrnt** [comment]
@xuetengfei 
How did you configure it? Mine is simply `PROJECT_DIRECTORY`: `projects`, which makes it search `~/projects`. If you'd prefer to use an absolute path, I could add support for that as well. :)

**Comment by bjrnt** [comment]
I've added support for absolute paths in the latest version, as I think that should be supported. Feel free to give it another try.

**Comment by xuetengfei** [comment]
Thank you very much. The 1.2.1 release   absolute paths is work. I'm already using it.
