### ISSUE TITLE
runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by sergejvoronov** [bjrnt/alfred-project-manager#21]
Hello @bjrnt, 

Having an issue using project manager, getting an error `runtime error: slice bounds out of range` with the latest 1.4.0 version:
![image](https://github.com/bjrnt/alfred-project-manager/assets/20336797/01b26518-4b1e-4321-b901-53d41b0cbe3b)

**Comment by sergejvoronov** [comment]
debug stack trace:
```
[14:31:48.890] Project Manager[Script Filter] Queuing argument 'aut'
[14:31:49.314] Project Manager[Script Filter] Script with argv 'aut' finished
[14:31:49.321] ERROR: Project Manager[Script Filter] Code 1: 🍺
14:31:48 workflow.go:328: ------ Project Manager/1.4.0 (AwGo/0.27.1) -------
14:31:48 cache.go:22: Cache does not exist or has expired -- skipping cache
14:31:49 workflow.go:343: ------------------ FATAL ERROR -------------------
14:31:49 workflow.go:344: runtime error: slice bounds out of range [15:10] : goroutine 1 [running]:
runtime/debug.Stack(0xc0000e37f0, 0x1, 0x1)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/deanishe/awgo.(*Workflow).Run.func2(0xc0000d0120)
	/Users/tegelund/go/pkg/mod/github.com/deanishe/awgo@v0.28.0/workflow.go:344 +0xeb
panic(0x1155ea0, 0xc0000c2ae0)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
main.urlForOrigin(0xc0000c2ac0, 0x1e, 0xc0000c2ac0, 0x1e)
	/Users/tegelund/Desktop/alfred-project-manager/repo.go:46 +0x1ea
main.RepoURL(0xc0000ad2f0, 0x26, 0xc0000e3b78, 0x112907f, 0x0, 0x0)
	/Users/tegelund/Desktop/alfred-project-manager/repo.go:27 +0x125
main.NewProjectFromPath(0xc0000ad2f0, 0x26, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/tegelund/Desktop/alfred-project-manager/project.go:15 +0x5a
main.scanDirAtPath(0xc000014092, 0x1f, 0x0, 0x0, 0x1, 0x1, 0x10000c0000e3d88, 0x4, 0x1f)
	/Users/tegelund/Desktop/alfred-project-manager/alfred-project-manager.go:37 +0x65c
main.scanProjects(0xc000090450, 0x0, 0x0, 0x0)
	/Users/tegelund/Desktop/alfred-project-manager/alfred-project-manager.go:54 +0x65
main.projects(0xc000090450, 0x0, 0x0, 0x2)
	/Users/tegelund/Desktop/alfred-project-manager/alfred-project-manager.go:62 +0x6c
main.run()
	/Users/tegelund/Desktop/alfred-project-manager/alfred-project-manager.go:75 +0x107
github.com/deanishe/awgo.(*Workflow).Run(0xc0000d0120, 0x1171608)
	/Users/tegelund/go/pkg/mod/github.com/deanishe/awgo@v0.28.0/workflow.go:358 +0x28b
main.main()
	/Users/tegelund/Desktop/alfred-project-manager/alfred-project-manager.go:90 +0x39
14:31:49 workflow.go:345: ---------------- END STACK TRACE -----------------
14:31:49 feedback.go:481: Sent 1 result(s) to Alfred
14:31:49 workflow.go:376: [ERROR] runtime error: slice bounds out of range [15:10]
14:31:49 workflow.go:402: ------------------ 393.364708ms ------------------
[14:31:49.323] Project Manager[Script Filter] {
  "variables": {
    "AW_SESSION_ID": "RBANGXUH0C57XFWWY4SPZGJL"
  },
  "items": [
    {
      "title": "runtime error: slice bounds out of range [15:10]",
      "valid": false,
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
      }
    }
  ]
}
```

**Comment by bjrnt** [comment]
Hi @sergejvoronov, 

Thanks for reporting the bug!

It seems like there's some issue in parsing the remote URL for one or more of your repos for some reason. I'd be glad to patch this for you, but it would break the ability to open the repo's URL in the browser through the workflow. 

To keep this functionality working for you, would you be able to share the format of the values you get when you run `git remote get-url origin` within the repos in the directory you configured the workflow for? Feel free to obfuscate any actual values, I'm only interested in the format, e.g. `git@github.com:user/repo.git`. It looks like the workflow is running into issues parsing some origin URL that starts with `git@github.com` but does not follow the above pattern.

**Comment by sergejvoronov** [comment]
Thanks for a quick reply!

I have lots of repos in that directory, but found one repo with a different origin path than the others:
`git@github.com:xxxxx/go-nsq`, it does not use `.git` ending. I've deleted it, and it fixed the issue, but it means I cannot use that repo with your Project Manager :)

Also, I have another issue: when I clone a new repo to the directory it does not instantly appear in the Alfred results, I need to wait some time to be able to find it through Alfred. I bet there is some issue with the cache, it does not recognize when a new repo is cloned to rebuild the cache or something like that.

**Comment by bjrnt** [comment]
Thanks for reporting these issues!

Would you give this version of the workflow a try? 
[alfred-project-manager-1.5.0.alfredworkflow.zip](https://github.com/bjrnt/alfred-project-manager/files/13955959/alfred-project-manager-1.5.0.alfredworkflow.zip)

It should fix both of the issues you described.

**Comment by sergejvoronov** [comment]
Looks like I am still getting the same error with that particular repo without `.git` ending cloned in my directory :(
Alfred debugger shows the same stack trace.

But the cache issue is solved now 👍

**Comment by sergejvoronov** [comment]
hey, @bjrnt,

Are there any updates? 🙏 I found some more repositories which cause the same runtime error.

**Comment by bjrnt** [comment]
Hi @sergejvoronov , 

Sorry about the delay! Do you want to give this version a try? It should work if all of the other repos follow the same `git@github.com:xxxx/abc` (without `.git`) pattern.

[alfred-project-manager-1.5.0.alfredworkflow.zip](https://github.com/bjrnt/alfred-project-manager/files/14092333/alfred-project-manager-1.5.0.alfredworkflow.zip)

**Comment by sergejvoronov** [comment]
> Hi @sergejvoronov ,
> 
> Sorry about the delay! Do you want to give this version a try? It should work if all of the other repos follow the same `git@github.com:xxxx/abc` (without `.git`) pattern.
> 
> [alfred-project-manager-1.5.0.alfredworkflow.zip](https://github.com/bjrnt/alfred-project-manager/files/14092333/alfred-project-manager-1.5.0.alfredworkflow.zip)

Thanks @bjrnt!

Now it works flawlessly! 👍

**Comment by bjrnt** [comment]
Awesome I'm happy to hear that! I'll cut a new release with the patches :)
